apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.labels.AppName }}
  name: {{ .Values.labels.AppName }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  ports:
    - port:  {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  selector:
    run: {{ .Values.labels.AppName }}

